### PR TITLE
Fix code according to previous suggestions

### LINKED ISSUE #28: Clean up code from previous PRs
* Rename `result` variable in components to image or featuredImage or something like that.
* Gatsby can recieve field in objects too:
```
status: {
  label: 'Áll',
  color: 'red',
}
```
* Delete unwanted comments https://github.com/kir-dev/blog-next/pull/26#discussion_r640793123 
* Change text align in first section

### PR DESCRIPTION
**Pull request by triszt4n**
Closes #28

### CODE REVIEW

File: src/components/blog-components/BlogAuthor.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const BlogAuthor: React.FC<BlogAuthorProps> = ({ date, name, hasLongDate }) => {
         </HStack>
       ) : (
         <Box>
-          <Text as={Link} fontWeight="medium" fontSize="md" to={`https://pek.k8s.sch.bme.hu/profiles/${name}/`}>
+          <Text as={Link} fontWeight="medium" fontSize="md" to={`${pekUrl}/profiles/${name}/`}>
```
Comment (OmTheTurtle) [inline src/components/blog-components/BlogAuthor.tsx:40]: This `pekUrl` variable is just a redeclaration of the imported PEK_URL, right? Can't we just use the imported one?

Comment (triszt4n) [reply src/components/blog-components/BlogAuthor.tsx:40]: Nice catch, chief, gone over this, gonna mend it

**Review by OmTheTurtle — APPROVED** [review]

**Review by OmTheTurtle — APPROVED** [review]

**Review by balintkiraly — APPROVED** [review]
